language: generic
sudo: required # need this to execute build
services:
  - docker

before_install:
  - docker build -t kap16/docker-react -f Dockerfile.dev .

script: # contains scripts when our test need to run
  - docker run -e CI=true kap16/docker-react npm run test